title: Consumer Product Safety Office
url: https://www.consumerproductsafety.gov.sg
favicon: /images/cpso-logo.png
colors:
  primary-color: "#6031b6"
  secondary-color: "#4372d6"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
google_analytics: UA-198468316-1
resources_name: news-and-media
future: true
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
description: The Consumer Product Safety Office (CPSO) is an office overseen by
  Enterprise Singapore that is responsible for implementing the Consumer
  Protection (Safety Requirements) Regulations (CPSR) and Consumer Protection
  (Consumer Goods Safety Requirements) Regulations 2011 (CGSR).
staging: https://enterprisesg-cpso-staging.netlify.app
prod: https://enterprisesg-cpso-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
shareicon: /images/isomer-logo.svg
is_government: false
facebook-pixel: ""
linkedin-insights: ""
google_analytics_ga4: "396161412"
